#! /bin/bash
sudo pip install pylint
pip install flake8
pip install flake8-docstrings
apm install symbols-tree-view
apm install merge-conflicts
apm install pigments
apm install color-picker
apm install linter
apm install linter-flake8
apm install script
apm install concourse-vis
apm install open-recent
apm install todo-show
apm install highlight-selected
apm install atom-beautify
apm install auto-detect-indentation
apm install file-icons
apm install git-plus
apm install emmet
apm install zen
apm install dash
apm install date
apm install linter-write-good
apm install linter-pylint
apm install jsonlint
apm install regex-railroad-diagram
apm install sort-lines
apm install atom-python-run
apm install atom-python-test
apm install autocomplete-python
apm install browser-plus
apm install git-projects
apm install hyperclick
apm install language-scala
apm install project-manager
apm install python-autopep8
apm install python-debugger
apm install python-indent
apm install python-jedi
apm install python-tools
